sudo: false
language: python
cache: pip

matrix:
  include:
    - python: 2.7
      env: DJANGO="Django>=1.8,<1.9"
    - python: 3.2
      env: DJANGO="Django>=1.8,<1.9"
    - python: 3.3
      env: DJANGO="Django>=1.8,<1.9"
    - python: 3.4
      env: DJANGO="Django>=1.8,<1.9"
    - python: 3.5
      env: DJANGO="Django>=1.8,<1.9"
    - python: 2.7
      env: DJANGO="Django>=1.9,<1.10"
    - python: 3.4
      env: DJANGO="Django>=1.9,<1.10"
    - python: 3.5
      env: DJANGO="Django>=1.9,<1.10"
    - python: 2.7
      env: DJANGO="Django>=1.10,<1.11"
    - python: 3.4
      env: DJANGO="Django>=1.10,<1.11"
    - python: 3.5
      env: DJANGO="Django>=1.10,<1.11"
    - python: 2.7
      env: DJANGO="Django>=1.11,<2.0"
    - python: 3.4
      env: DJANGO="Django>=1.11,<2.0"
    - python: 3.5
      env: DJANGO="Django>=1.11,<2.0"
    - python: 3.6
      env: DJANGO="Django>=1.11,<2.0"

install:
 - pip install $DJANGO
 - pip install flake8
 - pip install -e .

before_script:
  - flake8

script: ./runtests.sh
